/**
 * Generic snippet extractor — zero project coupling, runs on Node and Bun.
 *
 * Extracts the `#region snippet` block from each `*.ts` module in a source
 * directory and emits a generated module keyed by file name. Each module is
 * assumed to be type-checked / tested by the consumer's gate, so every rendered
 * snippet compiles against the real API.
 *
 * Each entry has two forms:
 *  - `code`: display snippet (region only, `export` stripped, fixture imports
 *    dropped, imports optionally rewritten to package specifiers).
 *  - `twoslash`: self-contained module for twoslash — shown imports at the top,
 *    fixtures hidden inside `---cut-start/end---`, body below — so twoslash
 *    compiles the whole thing but renders only the snippet, with hover types.
 *
 * The engine is split into a pure core (`buildSnippetsModule`) and an IO wrapper
 * (`extractSnippets`) so the transform logic is unit-testable without a disk.
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

export interface SnippetForms {
  code: string;
  twoslash: string;
}

export interface ExtractSnippetsOptions {
  /** Directory scanned for `*.ts` snippet modules. */
  srcDir: string;
  /** Path of the generated module to write. */
  outFile: string;
  /**
   * Basename (no extension) of the shared fixtures module inside `srcDir`.
   * Its imports are hidden behind `---cut---` in the twoslash form and dropped
   * from the display form. Default: `"fixtures"`.
   */
  fixtureName?: string;
  /**
   * Rewrites a single import line — e.g. relative source paths to published
   * package specifiers. Default: identity (no rewrite).
   */
  rewriteImport?: (line: string) => string;
  /** Human label for the generated-file header comment. Default: `srcDir`. */
  sourceLabel?: string;
  /** Attribution shown in the `// Generated by …` header. Default: `"extract-snippets"`. */
  generatedBy?: string;
}

const identity = (l: string) => l;

const isImport = (l: string) => /^\s*import\b/.test(l);
const stripExport = (l: string) => l.replace(/^(\s*)export /, "$1");

const fixtureImportMatcher =
  (fixtureName: string) =>
  (l: string): boolean =>
    new RegExp(`from\\s+["'][^"']*${fixtureName}[^"']*["']`).test(l);

const trim = (lines: string[]): string[] => {
  const out = [...lines];
  while (out.length > 0 && out[0]?.trim() === "") out.shift();
  while (out.length > 0 && out[out.length - 1]?.trim() === "") out.pop();
  return out;
};

const regionLines = (source: string): string[] | null => {
  const lines = source.split("\n");
  const start = lines.findIndex((l) => l.includes("#region snippet"));
  const end = lines.findIndex((l) => l.includes("#endregion"));
  if (start === -1 || end === -1 || end <= start) return null;
  return lines.slice(start + 1, end);
};

// Drop bindings from a hidden fixture import that the shown region already
// imports from the same module — otherwise twoslash sees duplicate identifiers.
const dedupeFixtureImports = (fixtureImports: string[], regionImports: string[]): string[] => {
  const named = new Map<string, Set<string>>(); // module -> shown binding names
  const namespaces = new Set<string>(); // modules the region imports `* as`
  for (const l of regionImports) {
    const ns = l.match(/^import \* as \w+ from "([^"]+)"/);
    if (ns?.[1]) {
      namespaces.add(ns[1]);
      continue;
    }
    const m = l.match(/^import (?:type )?\{ (.+?) \} from "([^"]+)"/);
    if (m?.[1] && m[2]) {
      const set = named.get(m[2]) ?? new Set<string>();
      for (const b of m[1].split(",")) set.add(b.trim().replace(/^type /, ""));
      named.set(m[2], set);
    }
  }
  const out: string[] = [];
  for (const l of fixtureImports) {
    const ns = l.match(/^import \* as \w+ from "([^"]+)"/);
    if (ns?.[1]) {
      if (!namespaces.has(ns[1])) out.push(l);
      continue;
    }
    const m = l.match(/^(import (?:type )?\{ )(.+?)( \} from ")([^"]+)(";?)$/);
    if (m?.[2] && m[4]) {
      const have = named.get(m[4]);
      const kept = m[2]
        .split(",")
        .map((s) => s.trim())
        .filter((b) => !have?.has(b.replace(/^type /, "")));
      if (kept.length > 0) out.push(`${m[1]}${kept.join(", ")}${m[3]}${m[4]}${m[5]}`);
      continue;
    }
    out.push(l);
  }
  return out;
};

interface TransformDeps {
  isFixtureImport: (l: string) => boolean;
  rewriteImport: (l: string) => string;
}

// Plain display form: region without fixture imports / exports.
const toDisplay = (region: string[], { isFixtureImport, rewriteImport }: TransformDeps): string =>
  trim(region.filter((l) => !isFixtureImport(l)).map((l) => stripExport(rewriteImport(l)))).join(
    "\n",
  );

// Twoslash form: shown imports, hidden fixtures, shown body.
const toTwoslash = (region: string[], fixtures: string, deps: TransformDeps): string => {
  const { isFixtureImport, rewriteImport } = deps;
  const fx = fixtures.split("\n");
  const regionImports = region.filter((l) => isImport(l) && !isFixtureImport(l)).map(rewriteImport);
  const regionBody = trim(region.filter((l) => !isImport(l)).map(stripExport));
  const fixtureImports = dedupeFixtureImports(
    fx.filter(isImport).map(rewriteImport),
    regionImports,
  );
  const fixtureBody = trim(fx.filter((l) => !isImport(l)));
  return [
    ...regionImports,
    "// ---cut-start---",
    ...fixtureImports,
    ...fixtureBody,
    "// ---cut-end---",
    ...regionBody,
  ].join("\n");
};

export interface BuildResult {
  /** Generated module text, ready to write. */
  module: string;
  /** Snippet ids included, sorted. */
  ids: string[];
  /** Module names skipped because they had no `#region snippet`. */
  skipped: string[];
}

/**
 * Pure core: given raw module sources + the fixtures source, produce the
 * generated module text. No disk access — unit-testable.
 */
export function buildSnippetsModule(
  modules: { name: string; source: string }[],
  fixturesSource: string,
  opts: Pick<
    ExtractSnippetsOptions,
    "fixtureName" | "rewriteImport" | "sourceLabel" | "generatedBy"
  > = {},
): BuildResult {
  const fixtureName = opts.fixtureName ?? "fixtures";
  const deps: TransformDeps = {
    isFixtureImport: fixtureImportMatcher(fixtureName),
    rewriteImport: opts.rewriteImport ?? identity,
  };

  const entries: [string, SnippetForms][] = [];
  const skipped: string[] = [];
  for (const { name, source } of modules) {
    const region = regionLines(source);
    if (region === null) {
      skipped.push(name);
      continue;
    }
    entries.push([
      name,
      { code: toDisplay(region, deps), twoslash: toTwoslash(region, fixturesSource, deps) },
    ]);
  }

  entries.sort(([a], [b]) => a.localeCompare(b));

  const body = entries
    .map(
      ([id, v]) =>
        `  ${JSON.stringify(id)}: { code: ${JSON.stringify(v.code)}, twoslash: ${JSON.stringify(v.twoslash)} },`,
    )
    .join("\n");
  const label = opts.sourceLabel ?? "the source directory";
  const generatedBy = opts.generatedBy ?? "extract-snippets";
  const module = `// Generated by ${generatedBy} — do not edit.\n// Source: ${label} (type-checked + tested by the gate).\nexport const snippets = {\n${body}\n} as const;\n\nexport type SnippetId = keyof typeof snippets;\n`;

  return { module, ids: entries.map(([id]) => id), skipped };
}

export interface ExtractResult {
  count: number;
  outFile: string;
  skipped: string[];
}

/**
 * IO wrapper: scan `srcDir` for `*.ts`, read the fixtures module, build the
 * generated module and write it to `outFile`.
 */
export async function extractSnippets(opts: ExtractSnippetsOptions): Promise<ExtractResult> {
  const fixtureName = opts.fixtureName ?? "fixtures";
  const fixturesSource = await readFile(resolve(opts.srcDir, `${fixtureName}.ts`), "utf8");

  const dirents = await readdir(opts.srcDir, { withFileTypes: true });
  const modules: { name: string; source: string }[] = [];
  for (const dirent of dirents) {
    if (!dirent.isFile() || !dirent.name.endsWith(".ts")) continue;
    const name = dirent.name.replace(/\.ts$/, "");
    if (name === fixtureName) continue;
    modules.push({ name, source: await readFile(resolve(opts.srcDir, dirent.name), "utf8") });
  }

  const { module, ids, skipped } = buildSnippetsModule(modules, fixturesSource, {
    fixtureName,
    sourceLabel: opts.sourceLabel ?? opts.srcDir,
    ...(opts.rewriteImport ? { rewriteImport: opts.rewriteImport } : {}),
    ...(opts.generatedBy !== undefined ? { generatedBy: opts.generatedBy } : {}),
  });

  await mkdir(dirname(opts.outFile), { recursive: true });
  await writeFile(opts.outFile, module);
  return { count: ids.length, outFile: opts.outFile, skipped };
}
