import { afterAll, describe, expect, it } from "bun:test";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { buildSnippetsModule, extractSnippets } from "../src/index.js";

const fixtures = [
  'import { stub } from "./fixtures.js";',
  "export const helper = () => stub;",
].join("\n");

// biome-ignore lint/complexity/noExcessiveLinesPerFunction: test suite contains many test cases
describe("buildSnippetsModule", () => {
  it("extracts the region, strips exports, and drops fixture imports from the display form", () => {
    const source = [
      'import { stub } from "./fixtures.js";',
      "// #region snippet",
      "export const value = stub + 1;",
      "// #endregion",
    ].join("\n");

    const { module, ids } = buildSnippetsModule([{ name: "ex", source }], fixtures);

    expect(ids).toEqual(["ex"]);
    // Display form: region only, no `export`, no fixture import.
    expect(module).toContain('"ex": { code: "const value = stub + 1;"');
    expect(module).not.toContain('code: "import { stub }');
  });

  it("hides fixtures behind cut markers in the twoslash form", () => {
    const source = ["// #region snippet", "export const v = helper();", "// #endregion"].join("\n");
    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures);

    // The twoslash payload is JSON-escaped in the emitted module.
    expect(module).toContain("// ---cut-start---");
    expect(module).toContain("// ---cut-end---");
    expect(module).toContain("const helper = () => stub;");
  });

  it("applies a custom import rewriter to region imports", () => {
    const source = [
      "// #region snippet",
      'import { x } from "../../result/src/index.js";',
      "export const out = x;",
      "// #endregion",
    ].join("\n");

    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures, {
      rewriteImport: (l) =>
        l.replace(/from "(?:\.\.\/)+result\/src\/index\.js"/, 'from "@scope/result"'),
    });

    expect(module).toContain('import { x } from \\"@scope/result\\"');
  });

  it("skips modules without a snippet region", () => {
    const { ids, skipped } = buildSnippetsModule(
      [{ name: "no-region", source: "export const x = 1;" }],
      fixtures,
    );
    expect(ids).toEqual([]);
    expect(skipped).toEqual(["no-region"]);
  });

  it("emits a typed `as const` module with a SnippetId type", () => {
    const source = ["// #region snippet", "const a = 1;", "// #endregion"].join("\n");
    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures, {
      generatedBy: "test",
    });
    expect(module).toContain("// Generated by test — do not edit.");
    expect(module).toContain("} as const;");
    expect(module).toContain("export type SnippetId = keyof typeof snippets;");
  });
});

describe("extractSnippets (filesystem IO)", () => {
  const FIXTURES = resolve(import.meta.dir, "fixtures");
  let outFile = "";

  afterAll(async () => {
    if (outFile) await rm(outFile.replace(/\/[^/]+$/, ""), { recursive: true, force: true });
  });

  it("scans a directory, skips fixtures, and writes the generated module", async () => {
    const dir = await mkdtemp(join(tmpdir(), "twoslash-"));
    outFile = join(dir, "snippets.generated.ts");

    const result = await extractSnippets({ srcDir: FIXTURES, outFile });

    expect(result.count).toBe(1); // example.ts in; fixtures.ts skipped
    expect(result.outFile).toBe(outFile);

    const written = await readFile(outFile, "utf8");
    expect(written).toContain('"example": { code: "const value = stub + 1;"');
    expect(written).toContain("// ---cut-start---");
  });
});
