import { afterAll, describe, expect, it } from "bun:test";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { buildSnippetsModule, extractSnippets } from "../src/index.js";

const fixtures = [
  'import { stub } from "./fixtures.js";',
  "export const helper = () => stub;",
].join("\n");

// biome-ignore lint/complexity/noExcessiveLinesPerFunction: test suite contains many test cases
describe("buildSnippetsModule", () => {
  it("extracts the region, strips exports, and drops fixture imports from the display form", () => {
    const source = [
      'import { stub } from "./fixtures.js";',
      "// #region snippet",
      "export const value = stub + 1;",
      "// #endregion",
    ].join("\n");

    const { module, ids } = buildSnippetsModule([{ name: "ex", source }], fixtures);

    expect(ids).toEqual(["ex"]);
    // Display form: region only, no `export`, no fixture import.
    expect(module).toContain('"ex": { code: "const value = stub + 1;"');
    expect(module).not.toContain('code: "import { stub }');
  });

  it("hides fixtures behind cut markers in the twoslash form", () => {
    const source = ["// #region snippet", "export const v = helper();", "// #endregion"].join("\n");
    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures);

    // The twoslash payload is JSON-escaped in the emitted module.
    expect(module).toContain("// ---cut-start---");
    expect(module).toContain("// ---cut-end---");
    expect(module).toContain("const helper = () => stub;");
  });

  it("applies a custom import rewriter to region imports", () => {
    const source = [
      "// #region snippet",
      'import { x } from "../../result/src/index.js";',
      "export const out = x;",
      "// #endregion",
    ].join("\n");

    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures, {
      rewriteImport: (l) =>
        l.replace(/from "(?:\.\.\/)+result\/src\/index\.js"/, 'from "@scope/result"'),
    });

    expect(module).toContain('import { x } from \\"@scope/result\\"');
  });

  it("skips modules without a snippet region", () => {
    const { ids, skipped } = buildSnippetsModule(
      [{ name: "no-region", source: "export const x = 1;" }],
      fixtures,
    );
    expect(ids).toEqual([]);
    expect(skipped).toEqual(["no-region"]);
  });

  it("emits a typed `as const` module with a SnippetId type", () => {
    const source = ["// #region snippet", "const a = 1;", "// #endregion"].join("\n");
    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures, {
      generatedBy: "test",
    });
    expect(module).toContain("// Generated by test — do not edit.");
    expect(module).toContain("} as const;");
    expect(module).toContain("export type SnippetId = keyof typeof snippets;");
  });

  it("handles a fixtureName containing regex metacharacters without throwing", () => {
    const fx = 'import { stub } from "./test.helpers.js";\nexport const stub = 1;';
    const source = [
      'import { stub } from "./test.helpers.js";',
      "// #region snippet",
      "export const v = stub;",
      "// #endregion",
    ].join("\n");
    // "test.helpers" has a `.`; unescaped it would over-match (or "(" would throw).
    const run = () =>
      buildSnippetsModule([{ name: "ex", source }], fx, { fixtureName: "test.helpers" });
    expect(run).not.toThrow();
    // The fixture import is matched (and dropped from display), not leaked.
    expect(run().module).toContain('"ex": { code: "const v = stub;"');
  });

  it("treats CRLF input identically to LF", () => {
    const region = ["// #region snippet", "export const v = helper();", "// #endregion"];
    const lf = buildSnippetsModule([{ name: "ex", source: region.join("\n") }], fixtures);
    const crlf = buildSnippetsModule(
      [{ name: "ex", source: region.join("\r\n") }],
      fixtures.replace(/\n/g, "\r\n"),
    );
    expect(crlf.module).toBe(lf.module);
    expect(crlf.module).not.toContain("\\r");
  });

  it("dedupes a fixture's named binding the region already imports from the same module", () => {
    const fx = 'import { ok, err } from "@scope/result";\nexport const stub = ok(1);';
    const source = [
      "// #region snippet",
      'import { ok } from "@scope/result";',
      "export const v = ok(stub);",
      "// #endregion",
    ].join("\n");
    const { module } = buildSnippetsModule([{ name: "ex", source }], fx);
    // twoslash hides fixtures but must not re-import `ok` (region already shows it);
    // `err` is fixture-only and stays.
    expect(module).toContain('import { err } from \\"@scope/result\\"');
    expect(module).not.toContain('import { ok, err } from \\"@scope/result\\"');
  });

  it("drops a fixture's `* as` namespace import the region already brings in", () => {
    const fx = 'import * as R from "@scope/result";\nexport const stub = R.ok(1);';
    const source = [
      "// #region snippet",
      'import * as R from "@scope/result";',
      "export const v = R.ok(stub);",
      "// #endregion",
    ].join("\n");
    const { module } = buildSnippetsModule([{ name: "ex", source }], fx);
    // Inside the hidden cut region, the fixture's duplicate `* as R` is dropped
    // (the shown region already imports it); the fixture body stays.
    const cut = module.match(/---cut-start---([\s\S]*?)---cut-end---/)?.[1] ?? "";
    expect(cut).not.toContain("import * as R");
    expect(cut).toContain("stub = R.ok(1)");
  });
});

// biome-ignore lint/complexity/noExcessiveLinesPerFunction: test suite contains many test cases
describe("extractSnippets (filesystem IO)", () => {
  const FIXTURES = resolve(import.meta.dir, "fixtures");
  const tmpRoots: string[] = [];
  const tmpRoot = async () => {
    const dir = await mkdtemp(join(tmpdir(), "twoslash-"));
    tmpRoots.push(dir);
    return dir;
  };

  afterAll(async () => {
    await Promise.all(tmpRoots.map((d) => rm(d, { recursive: true, force: true })));
  });

  it("scans a directory, skips fixtures, and writes the generated module", async () => {
    const outFile = join(await tmpRoot(), "snippets.generated.ts");

    const result = await extractSnippets({ srcDir: FIXTURES, outFile });

    expect(result.count).toBe(1); // example.ts in; fixtures.ts skipped
    expect(result.outFile).toBe(outFile);

    const written = await readFile(outFile, "utf8");
    expect(written).toContain('"example": { code: "const value = stub + 1;"');
    expect(written).toContain("// ---cut-start---");
  });

  it("creates the outFile's parent directory when it does not exist", async () => {
    const outFile = join(await tmpRoot(), "nested", "deep", "snippets.generated.ts");

    const result = await extractSnippets({ srcDir: FIXTURES, outFile });

    expect(result.count).toBe(1);
    expect((await readFile(outFile, "utf8")).length).toBeGreaterThan(0);
  });

  it("scans .tsx snippet modules (JSX) alongside .ts", async () => {
    const dir = await tmpRoot();
    await writeFile(
      join(dir, "fixtures.ts"),
      "export const Wrap = (p: { children: unknown }) => p;\n",
    );
    await writeFile(
      join(dir, "badge.tsx"),
      [
        'import { Wrap } from "./fixtures.js";',
        "// #region snippet",
        "export const Badge = () => <Wrap>{1}</Wrap>;",
        "// #endregion",
      ].join("\n"),
    );
    const outFile = join(dir, "snippets.generated.ts");

    const result = await extractSnippets({ srcDir: dir, outFile });

    expect(result.count).toBe(1); // badge.tsx in; fixtures.ts skipped
    expect((await readFile(outFile, "utf8")).length).toBeGreaterThan(0);
    expect(await readFile(outFile, "utf8")).toContain("<Wrap>{1}</Wrap>");
  });

  it("supports a .tsx fixtures module", async () => {
    const dir = await tmpRoot();
    await writeFile(join(dir, "fixtures.tsx"), "export const x = 1;\n");
    await writeFile(
      join(dir, "ex.ts"),
      ["// #region snippet", "export const v = x;", "// #endregion"].join("\n"),
    );

    const result = await extractSnippets({ srcDir: dir, outFile: join(dir, "out.ts") });

    expect(result.count).toBe(1);
  });
});
