#!/usr/bin/env bun
/**
 * Extracts the `#region snippet` block from each module in `@onrails/examples`
 * and writes them to `lib/snippets.generated.ts` keyed by file name. The example
 * modules are type-checked, linted, and unit-tested by the normal gate, so every
 * rendered snippet is guaranteed to compile against the real API.
 *
 * Transforms for display:
 *  - keep only the `// #region snippet` … `// #endregion` body
 *  - drop the leading `export ` (irrelevant to a reader)
 *  - rewrite the relative `../../<pkg>/src/...` imports to their package names
 */
import { resolve } from "node:path";
import { Glob } from "bun";

// Resolve paths from the script location so this runs from any cwd (e.g. as the
// docs prebuild, where cwd is apps/docs).
const REPO_ROOT = resolve(import.meta.dir, "../../..");
const SRC = resolve(REPO_ROOT, "packages/examples/src");
const OUT = resolve(import.meta.dir, "../lib/snippets.generated.ts");

const rewriteImport = (line: string): string =>
  line.replace(
    /from "(?:\.\.\/)+([\w-]+)\/src\/(.+?)\.js"/,
    (_m, pkg: string, rest: string) =>
      rest === "index" ? `from "@onrails/${pkg}"` : `from "@onrails/${pkg}/${rest}"`,
  );

const extractRegion = (source: string): string | null => {
  const lines = source.split("\n");
  const start = lines.findIndex((l) => l.includes("#region snippet"));
  const end = lines.findIndex((l) => l.includes("#endregion"));
  if (start === -1 || end === -1 || end <= start) return null;

  const body = lines
    .slice(start + 1, end)
    // hidden setup: imports of the local fixtures module never render
    .filter((l) => !/from\s+["'][^"']*fixtures[^"']*["']/.test(l))
    .map((l) => rewriteImport(l).replace(/^(\s*)export /, "$1"));

  // trim leading/trailing blank lines
  while (body.length > 0 && body[0]?.trim() === "") body.shift();
  while (body.length > 0 && body[body.length - 1]?.trim() === "") body.pop();
  return body.join("\n");
};

const entries: [string, string][] = [];
for await (const rel of new Glob("*.ts").scan(SRC)) {
  const name = rel.replace(/\.ts$/, "");
  if (name === "fixtures") continue;
  const code = extractRegion(await Bun.file(resolve(SRC, rel)).text());
  if (code === null) {
    console.warn(`skip ${rel}: no #region snippet`);
    continue;
  }
  entries.push([name, code]);
}

entries.sort(([a], [b]) => a.localeCompare(b));

const body = entries.map(([id, code]) => `  ${JSON.stringify(id)}: ${JSON.stringify(code)},`).join("\n");
const out = `// Generated by scripts/gen-snippets.ts — do not edit.\n// Source: packages/examples/src/*.ts (type-checked + tested by the gate).\nexport const snippets = {\n${body}\n} as const;\n\nexport type SnippetId = keyof typeof snippets;\n`;

await Bun.write(OUT, out);
console.log(`Wrote ${entries.length} snippets to ${OUT}`);
