import { describe, expect, it } from "bun:test";
import { buildSnippetsModule } from "../src/snippets.js";

const fixtures = [
  'import { stub } from "./fixtures.js";',
  "export const helper = () => stub;",
].join("\n");

// biome-ignore lint/complexity/noExcessiveLinesPerFunction: test suite contains many test cases
describe("buildSnippetsModule", () => {
  it("extracts the region, strips exports, and drops fixture imports from the display form", () => {
    const source = [
      'import { stub } from "./fixtures.js";',
      "// #region snippet",
      "export const value = stub + 1;",
      "// #endregion",
    ].join("\n");

    const { module, ids } = buildSnippetsModule([{ name: "ex", source }], fixtures);

    expect(ids).toEqual(["ex"]);
    // Display form: region only, no `export`, no fixture import.
    expect(module).toContain('"ex": { code: "const value = stub + 1;"');
    expect(module).not.toContain('code: "import { stub }');
  });

  it("hides fixtures behind cut markers in the twoslash form", () => {
    const source = ["// #region snippet", "export const v = helper();", "// #endregion"].join("\n");
    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures);

    // The twoslash payload is JSON-escaped in the emitted module.
    expect(module).toContain("// ---cut-start---");
    expect(module).toContain("// ---cut-end---");
    expect(module).toContain("const helper = () => stub;");
  });

  it("applies a custom import rewriter to region imports", () => {
    const source = [
      "// #region snippet",
      'import { x } from "../../result/src/index.js";',
      "export const out = x;",
      "// #endregion",
    ].join("\n");

    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures, {
      rewriteImport: (l) =>
        l.replace(/from "(?:\.\.\/)+result\/src\/index\.js"/, 'from "@scope/result"'),
    });

    expect(module).toContain('import { x } from \\"@scope/result\\"');
  });

  it("skips modules without a snippet region", () => {
    const { ids, skipped } = buildSnippetsModule(
      [{ name: "no-region", source: "export const x = 1;" }],
      fixtures,
    );
    expect(ids).toEqual([]);
    expect(skipped).toEqual(["no-region"]);
  });

  it("emits a typed `as const` module with a SnippetId type", () => {
    const source = ["// #region snippet", "const a = 1;", "// #endregion"].join("\n");
    const { module } = buildSnippetsModule([{ name: "ex", source }], fixtures, {
      generatedBy: "test",
    });
    expect(module).toContain("// Generated by test — do not edit.");
    expect(module).toContain("} as const;");
    expect(module).toContain("export type SnippetId = keyof typeof snippets;");
  });
});
